set ci-cd pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -82,5 +82,5 @@ jobs:
           if ! command -v pm2 &> /dev/null; then
             npm install -g pm2
           fi
-          pm2 start index.js --name taxi-ride || (echo "PM2 restart failed." && exit 1)
+          pm2 restart 17 || (echo "PM2 restart failed." && exit 1)
           EOF
